### PR TITLE
Allow time 1.10 and 1.11

### PR DESCRIPTION
**Pull request by sjakobi**
http://hackage.haskell.org/package/time-1.11/changelog

Tested locally with

    cabal test all --constraint 'time == 1.10'

and

    cabal test all --constraint 'time == 1.11'

### CODE REVIEW

**Comment by sjakobi** [comment]
The tests have timed out in the GHC-7.2 job. This appears to be unrelated to this patch – it has happened in previous builds too, e.g. https://travis-ci.org/github/haskell/test-framework/jobs/519237215.

**Comment by bergmark** [comment]
I filed a revision for this as a hackage trustee: http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/

**Comment by andreasabel** [comment]
This PR is outdated and subsumed by:
- #63

**Comment by sjakobi** [comment]
Closing as superseded by #63.

**Pull request closed without merging**
