### PR TITLE
Allow ansi-terminal-0.11

### PR DESCRIPTION
**Pull request by mpilgrem**
See https://github.com/commercialhaskell/stackage/issues/5592

### CODE REVIEW

**Comment by phadej** [comment]
@chessai what about this?

(be fair to contributors!)

**Comment by phadej** [comment]
Thanks!

**Comment by chessai** [comment]
Sorry, was linked to a specific PR and only checked that one out. Thanks for the patch!

**Comment by bergmark** [comment]
I filed a revision for this as a hackage trustee: http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/

**Pull request merged**
