### PR TITLE
Fix GHC 7.10/QuickCheck 2.8 warnings.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by hvr** [comment]
Thanks!

I guess the use of `#if !MIN_VERSION_base(4,8,0)` requires to rely on `cabal-version: >=1.10`?

**Comment by 23Skidoo** [comment]
> Have you tested the code still compiles with GHC 7.0?

Yes, that what I tested with.

**Comment by 23Skidoo** [comment]
> I guess the use of `#if !MIN_VERSION_base(4,8,0)` requires to rely on `cabal-version: >=1.10`?

Yes, though this form is already used in the code. Updated to require Cabal 1.10.

**Comment by hvr** [comment]
Thanks!

btw, kinda ironic that test-framework doesn't have a Travis-CI job yet... =)

**Pull request merged**
