### PR TITLE
Allow random-1.2

### PR DESCRIPTION
**Pull request by sjakobi**
Context: https://github.com/commercialhaskell/stackage/issues/5474

### CODE REVIEW

**Comment by asr** [comment]
If `random-1.2` requires `base >= 4.8 (GHC-7.10)` (see [Changelog](https://hackage.haskell.org/package/random-1.2.0/changelog)), why Travis is failing on GHC 7.0.4? Any idea?

Blocking https://github.com/agda/agda/issues/4792.

**Comment by sjakobi** [comment]
> If `random-1.2` requires `base >= 4.8 (GHC-7.10)` (see [Changelog](https://hackage.haskell.org/package/random-1.2.0/changelog)), why Travis is failing on GHC 7.0.4? Any idea?

I think [that job](https://travis-ci.org/github/haskell/test-framework/jobs/701555182) didn't use `random-1.2` at all. The line

> `constraints: random installed`

indicates that this job uses `random-1.0.0.3` which was bundled with GHC 7.0.4.

Apparently the job simply timed out while running the `test-framework-tests` testsuite. I don't see how this patch could have made a difference there though.

**Comment by sjakobi** [comment]
FWIW, I was able to build and test this project locally with `--constraint="random==1.2.*"` using this patch:


```diff
diff --git a/cabal.project b/cabal.project
index 43ea1e5..a65464c 100644
--- a/cabal.project
+++ b/cabal.project
@@ -8,5 +8,5 @@ packages: ./core
 
 -- On Debian/Ubuntu you may need the following to workaround an issue in libxml's packaging
 
--- package libxml
---     extra-include-dirs: /usr/include/libxml2
+package libxml
+    extra-include-dirs: /usr/include/libxml2
diff --git a/core/test-framework.cabal b/core/test-framework.cabal
index d1897a7..5617a2a 100644
--- a/core/test-framework.cabal
+++ b/core/test-framework.cabal
@@ -104,7 +104,7 @@ Test-Suite test-framework-tests
 
         -- Buildable:              False
         Build-Depends:          HUnit          >= 1.2
-                              , QuickCheck     >= 2.3 && < 2.14
+                              , QuickCheck     >= 2.3 && < 2.15
                               , base           >= 4.3
                               , random         >= 1.0
                               , containers     >= 0.1
```

Should I include the `QuickCheck` bump in this PR?

**Comment by asr** [comment]
> Should I include the `QuickCheck` bump in this PR?

I think so because [QuickCheck 2.14.1](https://hackage.haskell.org/package/QuickCheck-2.14.1/changelog) supports `random-1.2.`

**Comment by asr** [comment]
> FWIW, I was able to build and test this project locally with `--constraint="random==1.2.*"` using this patch:

Travis on GHC 7.0.4 failed again. Did you use this version of GHC?

**Comment by sjakobi** [comment]
`random-1.2` isn't compatible with GHC-7.0, but

```
cabal test all -w ghc-7.0.4
```

works for me locally.

I don't know why the testsuite timed out in CI.

**Comment by asr** [comment]
Travis is green! Could someone merge this PR and/or make a revision on Hackage, please.

**Comment by sjakobi** [comment]
Ping @phadej. Are you the current maintainer?

**Comment by phadej** [comment]
@sjakobi no.

**Comment by asr** [comment]
Any news?

**Comment by asr** [comment]
Any news?

**Comment by lehins** [comment]
@chessai Thank you for merging this PR. Any chance of getting these bounds revised on hackage?

**Comment by bergmark** [comment]
I filed a revision for this as a hackage trustee: http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/

**Pull request merged**
