### PR TITLE
Allow HUnit 1.4

### PR DESCRIPTION
**Pull request by paul-rouse**
I have checked this by using it for the tests of xmlhtml.

### CODE REVIEW

**Comment by hvr** [comment]
we need to verify a) whether test-framework reexports any HUnit-1.4's changed typesigs, and b) if that's the case, whether those type-sig changes require a major-ver bump in test-framework

**Comment by paul-rouse** [comment]
Only the package test-framework-hunit is affected by this change, and its only exports are

-   `testCase :: TestName -> Assertion -> Test`
-   `hUnitTestToTests :: Test -> [Test]`

`Test` and `TestName` are defined within test-framework, leaving just `Assertion` from HUnit - this is an alias defined as `type Assertion = IO ()` in both HUnit-1.3.x and 1.4.0.0, so I don't see any problem!

**Comment by paul-rouse** [comment]
Sorry - actually `Test` refers to two different things here (I misread the haddocks) - the parameter to `hUnitTestToTests` is `Test.HUnit.Base.Test`, but that is also unchanged between HUnit versions.

**Comment by glguy** [comment]
Updated on hackage

**Pull request closed without merging**
